/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components/containment/application': RouteRecordInfo<'/components/containment/application', '/components/containment/application', Record<never, never>, Record<never, never>>,
    '/components/containment/application2': RouteRecordInfo<'/components/containment/application2', '/components/containment/application2', Record<never, never>, Record<never, never>>,
    '/components/containment/application3': RouteRecordInfo<'/components/containment/application3', '/components/containment/application3', Record<never, never>, Record<never, never>>,
    '/features/theme': RouteRecordInfo<'/features/theme', '/features/theme', Record<never, never>, Record<never, never>>,
    '/getting-started/wireframes/baseline': RouteRecordInfo<'/getting-started/wireframes/baseline', '/getting-started/wireframes/baseline', Record<never, never>, Record<never, never>>,
    '/getting-started/wireframes/constrained': RouteRecordInfo<'/getting-started/wireframes/constrained', '/getting-started/wireframes/constrained', Record<never, never>, Record<never, never>>,
    '/getting-started/wireframes/inbox': RouteRecordInfo<'/getting-started/wireframes/inbox', '/getting-started/wireframes/inbox', Record<never, never>, Record<never, never>>,
    '/getting-started/wireframes/threecolumn': RouteRecordInfo<'/getting-started/wireframes/threecolumn', '/getting-started/wireframes/threecolumn', Record<never, never>, Record<never, never>>,
    '/styles-animations/borderRadius': RouteRecordInfo<'/styles-animations/borderRadius', '/styles-animations/borderRadius', Record<never, never>, Record<never, never>>,
    '/styles-animations/borders': RouteRecordInfo<'/styles-animations/borders', '/styles-animations/borders', Record<never, never>, Record<never, never>>,
    '/styles-animations/content': RouteRecordInfo<'/styles-animations/content', '/styles-animations/content', Record<never, never>, Record<never, never>>,
    '/styles-animations/display': RouteRecordInfo<'/styles-animations/display', '/styles-animations/display', Record<never, never>, Record<never, never>>,
    '/styles-animations/displayCss': RouteRecordInfo<'/styles-animations/displayCss', '/styles-animations/displayCss', Record<never, never>, Record<never, never>>,
    '/styles-animations/elevation': RouteRecordInfo<'/styles-animations/elevation', '/styles-animations/elevation', Record<never, never>, Record<never, never>>,
    '/styles-animations/material-color-palette': RouteRecordInfo<'/styles-animations/material-color-palette', '/styles-animations/material-color-palette', Record<never, never>, Record<never, never>>,
    '/styles-animations/text-typography': RouteRecordInfo<'/styles-animations/text-typography', '/styles-animations/text-typography', Record<never, never>, Record<never, never>>,
  }
}
